version: 2
jobs:
  build:
    docker:
      - image: node:6.7.0
    working_directory: ~/tmp
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: NPM Test
          command: npm test
